title: Ender
url: https://ender-coder.github.io
baseurl: ''
author: Ender

markdown: kramdown
kramdown:
  input: GFM # Github Flavored Markdown
  math_engine: katex # 防止行间公式渲染错误
permalink: /posts/:categories/:title # 博文目录

head: # 删改前确定知道自己在做什么
- tag: meta # Enable responsiveness on mobile devices
  var:
  - key: name
    value: viewport
  - key: content
    value: width=device-width, initial-scale=1.0, maximum-scale=1
- tag: meta
  var:
  - key: http-equiv
    value: X-UA-Compatible
  - key: content
    value: IE=edge
- tag: meta
  var:
  - key: http-equiv
    value: content-type
  - key: content
    value: 'text/html; charset=utf-8'
- tag: meta # google站点验证
  var:
  - key: name
    value: google-site-verification
  - key: content
    value: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
- tag: meta # baidu站点验证
  var:
  - key: name
    value: baidu-site-verification
  - key: content
    value: bEFDJ1LvXb
- tag: meta # yandex站点验证
  var:
  - key: name
    value: yandex-verification
  - key: content
    value: 52253e02830b443c
- tag: link
  var:
  - key: rel
    value: profile
  - key: href
    value: //gmpg.org/xfn/11
- tag: link # rss
  var:
  - key: rel
    value: alternate
  - key: href
    value: /atom.xml
  - key: title
    value: RSS
  - key: type
    value: application/rss+xml
- tag: link # 网站大图标
  var:
  - key: rel
    value: apple-touch-icon-precomposed
  - key: href
    value: /public/image/spider-man.jpg
- tag: link # 网站小图标
  var:
  - key: rel
    value: 'shortcut icon'
  - key: href
    value: /public/image/spider-man.jpg
- tag: link # 下面是博客的css，有些插件的css是单独在插件里引用的，假如需要自己的css可以仿照去加在后面
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/prism.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/poole.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/lanyon.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/style.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/wu-kan.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/ender.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.css # 在https://fontawesome.com/icons 查看支持的图标

body:
  theme-base: theme-base-0c # 可选的值08~0f
  layout-reverse: true # 开启后sidebar在右边，反之左边
  sidebar-overlay: true # 开启后正文不随sidebar移动而移动

script: # 需要在正文前调用的脚本
- var:
  - key: src
    value: //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js # jQuery
- var: 
  - key: src
    value: //cdn.jsdelivr.net/npm/ribbon.js/dist/ribbon.min.js # 彩带背景
  - key: alpha
    value: 0.3 # 彩带背景透明度
#- var:
#  - key: src
#    value: //cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js # 粒子特效背景
#  - key: color
#    value: '148,0,211' # 粒子线条颜色
#  - key: opacity
#    value: 1 # 粒子线条不透明度
- var:
  - key: src
    value: //cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/autoload.js # live2d
- var:
  - key: src
    value: /public/js/baidu_push.js # 百度推送
- var:
  - key: src
    value: /public/js/prism.js
- var:
  - key: src
    value: /public/js/mermaid.js
  - key: js
    value: //cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - key: stylesheet
    value: //cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css
  - key: markdown_expand
    value: true
- var:
  - key: src
    value: /public/js/katex.js
  - key: js
    value: //cdn.jsdelivr.net/npm/katex/dist/katex.min.js
  - key: auto_render
    value : //cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
  - key: stylesheet
    value: //cdn.jsdelivr.net/npm/katex/dist/katex.min.css
  - key: delimiters  # 开启行内公式$\KaTeX$支持
    value: true

sidebar:
  avatar: # 侧边栏显示的头像
    enable: true
    img: /public/image/spider-man.jpg # 头像的地址
    info: <br>SYSU18级在读<br>计算机类<br>喜欢捣鼓<br>热爱超英<br>坎爷nb # 头像背后的信息
  description: '<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=100% height=52 src="//music.163.com/outchain/player?type=2&id=441532&auto=0&height=32"></iframe>'
  social:
  - title: 1422112890 # qq
    class: 'fab fa-qq fa-fw'
  - title: Ender_520 # wechat
    class: 'fab fa-weixin fa-fw'
  - title: 1422112890@qq.com # email
    href: mailto:1422112890@qq.com
    class: 'fas fa-envelope fa-fw'
  - title: Ender # github
    href: //github.com/ender-coder
    class: 'fab fa-github fa-fw'
  - title: Ender # zhihu
    href: //www.zhihu.com/people/ender-95-27
    class: 'fab fa-zhihu fa-fw'

  nav:
  - title: '<i class="fas fa-home fa-fw"></i>  首页'
    href: /
  - title: '<i class="fas fa-tags fa-fw"></i>  标签'
    href: /tags
  - title: '<i class="fas fa-folder fa-fw"></i>  归档'
    href: /archive
  - title: '<i class="fas fa-comments fa-fw"></i>  留言'
    href: /comments
  - title: '<i class="fas fa-info-circle fa-fw"></i>  关于'
    href: /about

simple-jekyll-search:
  enable: true
  src: //cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js
  placeholder: 搜索博文
  noResultsText: 没有搜索到文章 # 无搜索数据提示语
  limit: 10 # 返回最大文章数
  fuzzy: false # 是否模糊匹配
  json: /public/simple-jekyll-search/search.json

jekyll-table-of-contents:
  enable: true

busuanzi:
  enable: true
  src: //cdn.jsdelivr.net/npm/busuanzi/bsz.pure.mini.js
  page_pv: # 阅读量
    alert: <i class="fas fa-book-reader fa-fw"></i> 被阅读
    unit: 次
  site_pv: # 访问量
    alert: <i class="fas fa-eye fa-fw"></i> 被访问
    unit: 次
  site_uv: # 访客量
    alert: <i class="fas fa-user-friends fa-fw"></i> 第
    unit: 位访客

run-time:
  enable: true
  start-time: '07/24/2019 00:00:00' # 这是我克隆博客并部署运行的第一天
  alert: <i class='fas fa-fan fa-spin fa-fw'></i> 努力运行
  day: 天
  hour: 时
  minute: 分
  second: 秒

copyright:
  enable: true
  text: '已开源于<a href="//github.com/Ender-coder/ender-coder.github.io">GitHub</a><br>'

post:
  meta:
    enable: true
    date: true
    wordcount:
      enable: true
      unit: 字
    readtime:
      enable: true
      unit: 分
      divided_by: 300
    visitor: # 需要开启valine的visitor选项使之开始计数; 可能会和busuanzi统计的有出入
      enable: true
      unit: 次
    copyright: '<i class="fab fa-creative-commons"></i>&nbsp;BY-SA 4.0（除特别声明或转载文章外）'
  related:
    enable: false
    title: 相关博文
  reward:
    enable: true
    text: 如果我的博客帮助到你，可以请我喝一杯奶茶~
    img: # 万一真的有人打赏呢~
    - id: wechat
      src: /public/image/wechatpay.png
    - id: alipay
      src: /public/image/alipay.jpg

valine:
  enable: true
  src: //cdn.jsdelivr.net/npm/valine
  appId: xViI6ucIqBOwXsIxB7YGyFWu-gzGzoHsz
  appKey: nJvn3U27Xay2sVJ3rXtOj5yB
  notify: true # 评论回复邮件提醒
  verify: true # 验证码服务
  avatar: identicon
  placeholder: 在这里评论吧！
  visitor: true # 文章访问量统计
  highlight: true # 代码高亮
  avatarForce: false # 每次访问强制拉取最新的评论列表头像
  recordIP: true # 记录评论者IP

friends:
  - name: wu-kan
    src: https://wu-kan.github.io
    description: 坎爷学长，在线教学，带我起飞
    portrait: /public/image/wu-kan.png
  - name: Max.C
    src: https://437436999.github.io
    description: 室友，一起快乐学习快乐打码~
    portrait: /public/image/Max.C.png
  - name: Reborn
    src: https://KomicaReborn.github.io
    description: 计科三人组×1
    portrait: /public/image/reborn.jpg
  - name: 林澈
    src: https://52hert-z.github.io
    description: 计科三人组×2
    portrait: /public/image/52hert-z.jpg
  - name: 米萨卡
    src: https://misaka-mikodo.github.io
    description: 浩腾神仙~
    portrait:  /public/image/misaka.jpeg
  

page404:
  search_children: # 腾讯公益
    enable: true
    src: //qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js
    charset: utf-8
    homePageUrl: '/'
    homePageName: 回到我的主页
